### ISSUE TITLE
when using t3-tool-cua: New Component wrong header import @my/ui

### ISSUE THREAD

**Issue by dufok** [albbus-stack/t3-cua-tools#1]
When creating new component, in head declares 
import { .. } from @my/ui

But it isn't work. Working is
import { .. } from "tamagui"

**Comment by albbus-stack** [comment]
I suggest you look into this: https://discord.com/channels/1062950158230372352/1067950318664560680/1068591705546309752

Please before opening an issue do you research in the discord.
